### ISSUE TITLE
Support DSL2

### ISSUE THREAD

**Issue by edmundmiller** [Emiller88/nextflow-mode#3]

**Comment by Mxrcon** [comment]
hey @Emiller88 Nice work on this mode, I'm interested on it, I still learning some elisp but i'm currently moving from vim to emacs, and I've worked on a syntax highlight for DSL2 on vim you may check it [here](https://github.com/Mxrcon/nextflow-vim/). 
I'm at you disposal, It seems that you'll just need to update the keywords and my syntax.vim may be useful on this task.

**Comment by edmundmiller** [comment]
@Mxrcon Lovely! I'll give your vim plugin ago and check out the code to see if I can add it. I've added support for most of the things, I'd still like some things like better imenu functionality.

**Comment by Mxrcon** [comment]
@Emiller88 that's really nice, I'll give your plugin as soon as have time, but i have a questions, is yout plugin able to understand nextflow.config as a nf file?

**Comment by edmundmiller** [comment]
@Mxrcon It is now! See 2c87bec8fcc6f2859d40839093c5e773724b45b5

**Comment by Mxrcon** [comment]
@Emiller88 Very nice addition, Thank you!

**Comment by edmundmiller** [comment]
Cherry-picked https://github.com/Emiller88/nextflow-mode/commit/f9b07a1205877c1aa5f671f7839cd144d8e40e07
