### ISSUE TITLE
Question: How to enable nextflow mode text highlighting etc

### ISSUE THREAD

**Issue by tamuanand** [Emiller88/nextflow-mode#9]
Hi

I have downloaded doom emacs and installed this package via doom and did doom sync.

```
Installing packages...
      - Checked out project: 125a1a8d15f998cd495ef6a6b981b1a0e201bd2f
      > Building project...
      - Checked out dired-git-info: 9461476a28a5fec0784260f6e318237c662c3430
      > Building dired-git-info...
      > Updating recipe repos...
      > Cloning nextflow-mode...macsmirror-mirror...
      > Building nextflow-mode...
      ✓ Installed 3 packages
```
When I am opening a new file called 'test.nf' and typing nextflow code, I do not see the necessary highlighting. Am I missing anything

Thanks

**Comment by edmundmiller** [comment]
There's very minimal highlighting right now. I need to update the syntax to support more of DSL2.

![image](https://user-images.githubusercontent.com/20095261/157259147-5278b7e6-3c18-4abf-95c2-9727a215b6d6.png)

Here's an example of what I get with `doom-one`, feel free to drop a screenshot if yours doesn't look like that!
